---
roles:
  - name: geerlingguy.security
  - name: geerlingguy.ntp
  - name: geerlingguy.docker
  - name: geerlingguy.pip

collections:
  - name: community.docker
  - name: community.general
  - name: community.crypto
  - name: ansible.posix
  - name: containers.podman
  - name: chocolatey.chocolatey