---
- name: Main
  hosts: all
  become: true
  
  roles:
    #- role: apps
    #- role: geerlingguy.security
    #- role: geerlingguy.ntp
    #- role: system
    #- role: security
    #- role: container
    - role: web