---
- name: Main playbook
  hosts: all
  become: true
  
  roles:
    - role: geerlingguy.security
    - role: geerlingguy.ntp
    - role: apps
    - role: system
    - role: security
    - role: container
