- name: Verify
  hosts: all
  gather_facts: yes
  tasks:
    - name: Check if user linger is enabled
      ansible.builtin.command: loginctl show-user {{ user }} | grep Linger=yes
      register: linger_check
      failed_when: linger_check.rc != 0
      changed_when: false
      when: user is defined
      ignore_errors: true
      
    - name: Check if /mnt/container directory exists
      ansible.builtin.stat:
        path: /mnt/container
      register: container_dir

    - name: Verify /mnt/container directory permissions
      ansible.builtin.assert:
        that:
          - container_dir.stat.exists
          - container_dir.stat.isdir
          - "'%04o' % container_dir.stat.mode == '0775'"
      when: container_dir.stat.exists
