---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost:
        private_ip: "127.0.0.1"
  variables:
    user: "ansible"
verifier:
  name: ansible