- name: Ensure GRUB configuration contains IOMMU option
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on"'
  notify: Update GRUB

- name: Check if IOMMU is already enabled
  ansible.builtin.command: dmesg | grep -e DMAR -e IOMMU
  register: proxmox_iommu_status
  changed_when: false
  ignore_errors: true 

- name: Load all drives
  ansible.builtin.command: find /dev/disk/by-id/ -type l|xargs -I{} ls -l {}|grep -v -E '[0-9]$' |sort -k11|cut -d' ' -f9,10,11,12
  register: proxmox_drives
  changed_when: false
  when: proxmox_iommu_status.stdout is search("IOMMU enabled")
  
- name: Print all drives
  ansible.builtin.debug:
      msg: "{{ proxmox_drives.stdout_lines }}"
  when: proxmox_iommu_status.stdout is search("IOMMU enabled")
