# OS
timezone: Europe/Amsterdam
locale: en_US.UTF-8
user: luki
group: luki
localhost: ip.srv
domain: wigger.one

# NTP
ntp_enabled: true
ntp_timezone: Europe/Amsterdam
ntp_manage_config: true
ntp_tinker_panic: true

# NTP server area configuration (leave empty for 'Worldwide').
# See: http://support.ntp.org/bin/view/Servers/NTPPoolServers
ntp_area: ''
ntp_servers:
  - "time.cloudflare.com iburst"
  - "time.google.com iburst"

ntp_restrict:
  - "127.0.0.1"
  - "::1"

# Security
security_ssh_port: 22
security_autoupdate_enabled: true
security_sshd_state: started
security_ssh_restart_handler_state: restarted
security_fail2ban_enabled: true

security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"

security_sudoers_passworded:
  - "{{ user }}"
  
# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: 'ce'
docker_packages:
  - "docker-{{ docker_edition }}"
  - "docker-{{ docker_edition }}-cli"
  - "docker-{{ docker_edition }}-rootless-extras"
  - "containerd.io"
  - docker-buildx-plugin
docker_packages_state: present


# Service options.
docker_service_manage: true
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

# Docker Compose Plugin options.
docker_install_compose_plugin: true
docker_compose_package: docker-compose-plugin
docker_compose_package_state: present

# Enable repo setup
docker_add_repo: true

# Docker repo URL.
docker_repo_url: https://download.docker.com/linux

# A list of users who will be added to the docker group.
docker_users: 
  - "{{ user }}"

# Python (pip) options.
pip_package: python3-pip
pip_executable: "{{ 'pip3' if pip_package.startswith('python3') else 'pip' }}"
pip_install_packages: ['requests']