- name: Create Discord directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0770"
    owner: "{{ user }}"
    group: "{{ group }}"
    recurse: true
  loop:
    - "/mnt/container/discord/doplarr"

- name: Set up Discord bots
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - src: container/doplarr.container.j2
      dest: "/home/{{ user }}/.config/containers/systemd/doplarr.container"
    - src: container/quadratauge.container.j2
      dest: "/home/{{ user }}/.config/containers/systemd/quadratauge.container"
    - src: env/doplarr/config.toml.j2
      dest: "/mnt/container/discord/doplarr/config.toml"
