---
- name: Install Dependencies for OS
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item }}"
    state: present
  loop:
    - office365proplus
    - microsoft-teams.install
    - vscode
    - firefox
    - ungoogled-chromium
    - thunderbird
    - minecraft-launcher
    - steam
    - goggalaxy
    - battle-net
    - ubisoft-connect
    - ea-app
    - discord
    - amd-radeon-adrenalin
  