---
- name: Install Dependencies for OS
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - epel-release
    - btop
    - zip
    - unzip
    - podman
  notify: Start podman
