---
- name: Create /mnt/container/bitwarden directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "/mnt/container/bitwarden/data"
    - "/mnt/container/bitwarden/logs"
    - "/mnt/container/bitwarden/db"

- name: Set up bitwarden environment variables
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - src: bitwarden/settings.env.j2
      dest: /mnt/container/bitwarden/settings.env
