---
- name: Create /mnt/container/social directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "/mnt/container/dendrite/db"
    - "/mnt/container/dendrite/media"
    - "/mnt/container/dendrite/config"
    - "/mnt/container/dendrite/jetstream"
    - "/mnt/container/dendrite/logs"
    - "/mnt/container/dendrite/search_index"
    - "/mnt/container/lemmy/config"
    - "/mnt/container/lemmy/db"
    - "/mnt/container/lemmy/pictrs"
    - "/mnt/container/mastodon/db"
    - "/mnt/container/mastodon/keydb"

- name: Set up social environment variables
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - src: lemmy/settings.env.j2
      dest: /mnt/container/lemmy/settings.env
    - src: lemmy/config/lemmy.hjson.j2
      dest: /mnt/container/lemmy/config/lemmy.hjson
    - src: mastodon/settings.env.j2
      dest: /mnt/container/mastodon/settings.env
    - src: dendrite/settings.env.j2
      dest: /mnt/container/dendrite/settings.env
    - src: dendrite/config/dendrite.yaml.j2
      dest: /mnt/container/dendrite/config/dendrite.yaml
    - src: dendrite/config/matrix_key.pem.j2
      dest: /mnt/container/dendrite/config/matrix_key.pem
