---
- name: Create /mnt/caddy directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "/mnt/caddy/data"
    - "/mnt/caddy/config"
    - "/mnt/caddy/logs"
    - "/mnt/caddy/www"

- name: Set up web environment variables
  ansible.builtin.template:
    src: "caddy/Caddyfile.{{ group_names | join('') }}.j2"
    dest: "/mnt/caddy/Caddyfile"
    mode: '0644'