- name: Create Lernmit directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
    owner: "{{ user }}"
    group: "{{ group }}"
    recurse: true
  loop:
    - "/mnt/container/lernmit/db"

- name: Set up Lernmit
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - src: container/lernmit-app.container.j2
      dest: "/home/{{ user }}/.config/containers/systemd/lernmit-app.container"
    - src: container/lernmit-db.container.j2
      dest: "/home/{{ user }}/.config/containers/systemd/lernmit-db.container"
    - src: env/settings.env.j2
      dest: "/mnt/container/lernmit/settings.env"
